In [3]:
from sklearn.tree import DecisionTreeRegressor
import pandas as pd

In [5]:
train_dataset=pd.read_csv('/home/aaic/Personal_Projects/Albany-Airbnb-Price-Prediction/central_data/feature_engineering/final_train_data.csv')
train_dataset.head()

,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,...,huizen,kingdom,london,netherlands,new,ny,paris,spain,united,utrecht
0,2016,1,100,75,0,1.0,0,1,1,5.514292,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
1,2018,4,100,73,1,1.0,0,1,1,5.514292,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
2,2013,4,100,53,0,6.0,0,1,1,5.415520,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,5,100,100,1,24.0,0,1,1,5.053609,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
4,2018,5,89,100,0,8.0,0,1,1,5.188696,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1.0,0.0

In [8]:
test_dataset=pd.read_csv('/home/aaic/Personal_Projects/Albany-Airbnb-Price-Prediction/central_data/feature_engineering/final_test_data.csv')
test_dataset.head()

,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,...,huizen,kingdom,london,netherlands,new,ny,paris,spain,united,utrecht
0,2016,5,100,98,1,2.0,0,1,1,5.386632,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,2013,2,33,50,0,1.0,0,1,1,5.517529,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
2,2012,1,100,0,0,1.0,0,1,1,5.053609,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,3,70,67,0,1.0,2,1,1,5.216495,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
4,2019,5,100,100,1,6.0,1,1,1,5.476502,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Data Preparation

X_train = train_dataset.drop('price', axis=1)
y_train = train_dataset['price']

X_test = test_dataset.drop('price', axis=1)
y_test = test_dataset['price']