In [2]:
from sklearn.tree import DecisionTreeRegressor
import pandas as pd
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
import inspect
from xgboost import XGBRegressor
import mlflow
import mlflow.sklearn
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [3]:
train_dataset=pd.read_csv('/home/aaic/Personal_Projects/Albany-Airbnb-Price-Prediction/central_data/feature_engineering/final_train_data.csv')
train_dataset.head()

,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,...,huizen,kingdom,london,netherlands,new,ny,paris,spain,united,utrecht
0,2016,1,100,75,0,1.0,0,1,1,5.514292,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
1,2018,4,100,73,1,1.0,0,1,1,5.514292,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
2,2013,4,100,53,0,6.0,0,1,1,5.415520,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,5,100,100,1,24.0,0,1,1,5.053609,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
4,2018,5,89,100,0,8.0,0,1,1,5.188696,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1.0,0.0

In [4]:
train_dataset.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4164 entries, 0 to 4163
Data columns (total 95 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   host_since                                    4164 non-null   int64
 1   host_response_time                            4164 non-null   int64
 2   host_response_rate                            4164 non-null   int64
 3   host_acceptance_rate                          4164 non-null   int64
 4   host_is_superhost                             4164 non-null   int64
 5   host_total_listings_count                     4164 non-null   float64
 6   host_verifications                            4164 non-null   int64
 7   host_has_profile_pic                          4164 non-null   int64
 8   host_identity_verified                        4164 non-null   int64
 9   neighbourhood_cleansed                        4164 non-null   float64
 10  latitude                                      4164 non-null   float64
 11  longitude                                     4164 non-null   float64
 12  property_type                                 4164 non-null   float64
 13  accommodates                                  4164 non-null   int64
 14  bathrooms                                     4164 non-null   float64
 15  bathrooms_text                                4164 non-null   float64
 16  bedrooms                                      4164 non-null   float64
 17  beds                                          4164 non-null   float64
 18  amenities                                     4164 non-null   int64
 19  price                                         4164 non-null   float64
 20  minimum_nights                                4164 non-null   int64
 21  maximum_nights                                4164 non-null   int64
 22  minimum_minimum_nights                        4164 non-null   float64
 23  maximum_minimum_nights                        4164 non-null   float64
 24  minimum_maximum_nights                        4164 non-null   float64
 25  maximum_maximum_nights                        4164 non-null   float64
 26  minimum_nights_avg_ntm                        4164 non-null   float64
 27  maximum_nights_avg_ntm                        4164 non-null   float64
 28  has_availability                              4164 non-null   int64
 29  availability_30                               4164 non-null   int64
 30  availability_60                               4164 non-null   int64
 31  availability_90                               4164 non-null   int64
 32  availability_365                              4164 non-null   int64
 33  number_of_reviews                             4164 non-null   int64
 34  number_of_reviews_ltm                         4164 non-null   int64
 35  number_of_reviews_l30d                        4164 non-null   int64
 36  availability_eoy                              4164 non-null   int64
 37  number_of_reviews_ly                          4164 non-null   int64
 38  first_review                                  4164 non-null   int64
 39  last_review                                   4164 non-null   int64
 40  review_scores_rating                          4164 non-null   float64
 41  review_scores_accuracy                        4164 non-null   float64
 42  review_scores_cleanliness                     4164 non-null   float64
 43  review_scores_checkin                         4164 non-null   float64
 44  review_scores_communication                   4164 non-null   float64
 45  review_scores_location                        4164 non-null   float64
 46  review_scores_value                           4164 non-null   float64
 47  instant_bookable                              4164 non-null   int64
 48  calculated_host_listings_count                4164 non-null   int64
 49  calculated_host_listings_count_entire_homes   4164 non-null   int64
 50  calculated_host_listings_count_private_rooms  4164 non-null   int64
 51  calculated_host_listings_count_shared_rooms   4164 non-null   int64
 52  reviews_per_month                             4164 non-null   float64
 53  room_type_Other                               4164 non-null   int64
 54  room_type_Private room                        4164 non-null   int64
 55  amsterdam                                     4164 non-null   float64
 56  apartment                                     4164 non-null   float64
 57  appartement                                   4164 non-null   float64
 58  canal                                         4164 non-null   float64
 59  center                                        4164 non-null   float64
 60  centre                                        4164 non-null   float64
 61  city                                          4164 non-null   float64
 62  cosy                                          4164 non-null   float64
 63  cozy                                          4164 non-null   float64
 64  family                                        4164 non-null   float64
 65  garden                                        4164 non-null   float64
 66  home                                          4164 non-null   float64
 67  house                                         4164 non-null   float64
 68  modern                                        4164 non-null   float64
 69  near                                          4164 non-null   float64
 70  private                                       4164 non-null   float64
 71  room                                          4164 non-null   float64
 72  spacious                                      4164 non-null   float64
 73  studio                                        4164 non-null   float64
 74  view                                          4164 non-null   float64
 75  amstelveen                                    4164 non-null   float64
 76  amsterdam.1                                   4164 non-null   float64
 77  belgium                                       4164 non-null   float64
 78  bergen                                        4164 non-null   float64
 79  brussels                                      4164 non-null   float64
 80  ca                                            4164 non-null   float64
 81  france                                        4164 non-null   float64
 82  germany                                       4164 non-null   float64
 83  groningen                                     4164 non-null   float64
 84  haarlem                                       4164 non-null   float64
 85  huizen                                        4164 non-null   float64
 86  kingdom                                       4164 non-null   float64
 87  london                                        4164 non-null   float64
 88  netherlands                                   4164 non-null   float64
 89  new                                           4164 non-null   float64
 90  ny                                            4164 non-null   float64
 91  paris                                         4164 non-null   float64
 92  spain                                         4164 non-null   float64
 93  united                                        4164 non-null   float64
 94  utrecht                                       4164 non-null   float64
dtypes: float64(64), int64(31)
memory usage: 3.0 MB

In [5]:
test_dataset=pd.read_csv('/home/aaic/Personal_Projects/Albany-Airbnb-Price-Prediction/central_data/feature_engineering/final_test_data.csv')
test_dataset.head()

,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,...,huizen,kingdom,london,netherlands,new,ny,paris,spain,united,utrecht
0,2016,5,100,98,1,2.0,0,1,1,5.386632,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,2013,2,33,50,0,1.0,0,1,1,5.517529,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
2,2012,1,100,0,0,1.0,0,1,1,5.053609,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,3,70,67,0,1.0,2,1,1,5.216495,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0
4,2019,5,100,100,1,6.0,1,1,1,5.476502,...,0.0,0.0,0.0,0.689919,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Data Preparation

X_train = train_dataset.drop('price', axis=1)
y_train = train_dataset['price']

X_test = test_dataset.drop('price', axis=1)
y_test = test_dataset['price']

In [7]:
mlflow.set_experiment("Algorithm Selection Experiment")  # All 3 runs will live under this experiment

# Run 1: Decision Tree 
with mlflow.start_run(run_name="Decision Tree"):
    # Define hyperparameters
    params = {"max_depth": 5, "min_samples_split": 10}
    
    # Log parameters BEFORE training
    mlflow.log_params(params)  # log_params() logs a dict at once
    
    # Train
    dt = DecisionTreeRegressor(**params)
    dt.fit(X_train, y_train)
    preds = dt.predict(X_test)
    
    # Log metrics AFTER training
    mlflow.log_metric("mean_absolute_error", mean_absolute_error(y_test, preds))
    mlflow.log_metric("mean_squared_error", mean_squared_error(y_test, preds))
    mlflow.log_metric('root_mean_squared_error', root_mean_squared_error(y_test, preds))
    
    # Save the model as an artifact
    mlflow.sklearn.log_model(dt, "decision_tree_model")

2026/04/20 09:44:40 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/04/20 09:44:40 INFO mlflow.store.db.utils: Updating database tables
2026/04/20 09:44:41 INFO mlflow.tracking.fluent: Experiment with name 'Algorithm Selection Experiment' does not exist. Creating a new experiment.
2026/04/20 09:44:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/20 09:44:42 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [8]:
# Run 2: Random Forest
with mlflow.start_run(run_name="Random Forest"):
    params = {"n_estimators": 60, "max_depth": 8, "min_samples_split": 5}
    
    mlflow.log_params(params)
    
    rf = RandomForestRegressor(**params)
    rf.fit(X_train, y_train)
    preds = rf.predict(X_test)
    
    mlflow.log_metric("mean_absolute_error", mean_absolute_error(y_test, preds))
    mlflow.log_metric("mean_squared_error", mean_squared_error(y_test, preds))
    mlflow.log_metric('root_mean_squared_error', root_mean_squared_error(y_test, preds))
    
    mlflow.sklearn.log_model(rf, "random_forest_model")

2026/04/20 09:44:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/20 09:44:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [9]:
# Run 3: XGBoost
with mlflow.start_run(run_name="XGBoost"):
    params = {"n_estimators": 200, "max_depth": 6, "learning_rate": 0.1, "subsample": 0.8}
    
    mlflow.log_params(params)
    
    xgb = XGBRegressor(**params)
    xgb.fit(X_train, y_train)
    preds = xgb.predict(X_test)
    
    mlflow.log_metric("mean_absolute_error", mean_absolute_error(y_test, preds))
    mlflow.log_metric("mean_squared_error", mean_squared_error(y_test, preds))
    mlflow.log_metric('root_mean_squared_error', root_mean_squared_error(y_test, preds))
    
    mlflow.xgboost.log_model(xgb, "xgboost_model")  # XGBoost has its own flavor

2026/04/20 09:45:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

In [49]:

inspect.signature(mean_absolute_error)

In [46]:
help(sklearn.metrics)

Help on package sklearn.metrics in sklearn:

NAME
    sklearn.metrics - Score functions, performance metrics, pairwise metrics and distance computations.

PACKAGE CONTENTS
    _base
    _classification
    _dist_metrics
    _pairwise_distances_reduction (package)
    _pairwise_fast
    _plot (package)
    _ranking
    _regression
    _scorer
    cluster (package)
    pairwise
    tests (package)

CLASSES
    builtins.object
        sklearn.metrics._dist_metrics.DistanceMetric
        sklearn.metrics._plot.confusion_matrix.ConfusionMatrixDisplay
        sklearn.metrics._plot.regression.PredictionErrorDisplay
    sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin(builtins.object)
        sklearn.metrics._plot.det_curve.DetCurveDisplay
        sklearn.metrics._plot.precision_recall_curve.PrecisionRecallDisplay
        sklearn.metrics._plot.roc_curve.RocCurveDisplay

    class ConfusionMatrixDisplay(builtins.object)
     |  ConfusionMatrixDisplay(confusion_matrix, *, display_labels=None)
     |
     |  Confusion Matrix visualization.
     |
     |  It is recommended to use
     |  :func:`~sklearn.metrics.ConfusionMatrixDisplay.from_estimator` or
     |  :func:`~sklearn.metrics.ConfusionMatrixDisplay.from_predictions` to
     |  create a :class:`ConfusionMatrixDisplay`. All parameters are stored as
     |  attributes.
     |
     |  For general information regarding `scikit-learn` visualization tools, see
     |  the :ref:`Visualization Guide <visualizations>`.
     |  For guidance on interpreting these plots, refer to the
     |  :ref:`Model Evaluation Guide <confusion_matrix>`.
     |
     |  Parameters
     |  ----------
     |  confusion_matrix : ndarray of shape (n_classes, n_classes)
     |      Confusion matrix.
     |
     |  display_labels : ndarray of shape (n_classes,), default=None
     |      Display labels for plot. If None, display labels are set from 0 to
     |      `n_classes - 1`.
     |
     |  Attributes
     |  ----------
     |  im_ : matplotlib AxesImage
     |      Image representing the confusion matrix.
     |
     |  text_ : ndarray of shape (n_classes, n_classes), dtype=matplotlib Text,             or None
     |      Array of matplotlib axes. `None` if `include_values` is false.
     |
     |  ax_ : matplotlib Axes
     |      Axes with confusion matrix.
     |
     |  figure_ : matplotlib Figure
     |      Figure containing the confusion matrix.
     |
     |  See Also
     |  --------
     |  confusion_matrix : Compute Confusion Matrix to evaluate the accuracy of a
     |      classification.
     |  ConfusionMatrixDisplay.from_estimator : Plot the confusion matrix
     |      given an estimator, the data, and the label.
     |  ConfusionMatrixDisplay.from_predictions : Plot the confusion matrix
     |      given the true and predicted labels.
     |
     |  Examples
     |  --------
     |  >>> import matplotlib.pyplot as plt
     |  >>> from sklearn.datasets import make_classification
     |  >>> from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
     |  >>> from sklearn.model_selection import train_test_split
     |  >>> from sklearn.svm import SVC
     |  >>> X, y = make_classification(random_state=0)
     |  >>> X_train, X_test, y_train, y_test = train_test_split(X, y,
     |  ...                                                     random_state=0)
     |  >>> clf = SVC(random_state=0)
     |  >>> clf.fit(X_train, y_train)
     |  SVC(random_state=0)
     |  >>> predictions = clf.predict(X_test)
     |  >>> cm = confusion_matrix(y_test, predictions, labels=clf.classes_)
     |  >>> disp = ConfusionMatrixDisplay(confusion_matrix=cm,
     |  ...                               display_labels=clf.classes_)
     |  >>> disp.plot()
     |  <...>
     |  >>> plt.show()
     |
     |  Methods defined here:
     |
     |  __init__(self, confusion_matrix, *, display_labels=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  plot(self, *, include_values=True, cmap='viridis', xticks_rotation='horizontal', values_format=None, ax=None, colorbar=True, im_kw=None, text_kw=None)
     |      Plot visualization.
     |
     |      Parameters
     |      ----------
     |      include_values : bool, default=True
     |          Includes values in confusion matrix.
     |
     |      cmap : str or matplotlib Colormap, default='viridis'
     |          Colormap recognized by matplotlib.
     |
     |      xticks_rotation : {'vertical', 'horizontal'} or float,                          default='horizontal'
     |          Rotation of xtick labels.
     |
     |      values_format : str, default=None
     |          Format specification for values in confusion matrix. If `None`,
     |          the format specification is 'd' or '.2g' whichever is shorter.
     |
     |      ax : matplotlib axes, default=None
     |          Axes object to plot on. If `None`, a new figure and axes is
     |          created.
     |
     |      colorbar : bool, default=True
     |          Whether or not to add a colorbar to the plot.
     |
     |      im_kw : dict, default=None
     |          Dict with keywords passed to `matplotlib.pyplot.imshow` call.
     |
     |      text_kw : dict, default=None
     |          Dict with keywords passed to `matplotlib.pyplot.text` call.
     |
     |          .. versionadded:: 1.2
     |
     |      Returns
     |      -------
     |      display : :class:`~sklearn.metrics.ConfusionMatrixDisplay`
     |          Returns a :class:`~sklearn.metrics.ConfusionMatrixDisplay` instance
     |          that contains all the information to plot the confusion matrix.
     |
     |  ----------------------------------------------------------------------
     |  Class methods defined here:
     |
     |  from_estimator(estimator, X, y, *, labels=None, sample_weight=None, normalize=None, display_labels=None, include_values=True, xticks_rotation='horizontal', values_format=None, cmap='viridis', ax=None, colorbar=True, im_kw=None, text_kw=None)
     |      Plot Confusion Matrix given an estimator and some data.
     |
     |      For general information regarding `scikit-learn` visualization tools, see
     |      the :ref:`Visualization Guide <visualizations>`.
     |      For guidance on interpreting these plots, refer to the
     |      :ref:`Model Evaluation Guide <confusion_matrix>`.
     |
     |      .. versionadded:: 1.0
     |
     |      Parameters
     |      ----------
     |      estimator : estimator instance
     |          Fitted classifier or a fitted :class:`~sklearn.pipeline.Pipeline`
     |          in which the last estimator is a classifier.
     |
     |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
     |          Input values.
     |
     |      y : array-like of shape (n_samples,)
     |          Target values.
     |
     |      labels : array-like of shape (n_classes,), default=None
     |          List of labels to index the confusion matrix. This may be used to
     |          reorder or select a subset of labels. If `None` is given, those
     |          that appear at least once in `y_true` or `y_pred` are used in
     |          sorted order.
     |
     |      sample_weight : array-like of shape (n_samples,), default=None
     |          Sample weights.
     |
     |      normalize : {'true', 'pred', 'all'}, default=None
     |          Either to normalize the counts display in the matrix:
     |
     |          - if `'true'`, the confusion matrix is normalized over the true
     |            conditions (e.g. rows);
     |          - if `'pred'`, the confusion matrix is normalized over the
     |            predicted conditions (e.g. columns);
     |          - if `'all'`, the confusion matrix is normalized by the total
     |            number of samples;
     |          - if `None` (default), the confusion matrix will not be normalized.
     |
     |      display_labels : array-like of shape (n_classes,), default=None
     |          Target names used for plotting. By default, `labels` will be used
     |          if it is defined, otherwise the unique labels of `y_true` and
     |          `y_pred` will be used.
     |
     |      include_values : bool, default=True
     |          Includes values in confusion matrix.
     |
     |      xticks_rotation : {'vertical', 'horizontal'} or float,                 default='horizontal'
     |          Rotation of xtick labels.
     |
     |      values_format : str, default=None
     |          Format specification for values in confusion matrix. If `None`, the
     |          format specification is 'd' or '.2g' whichever is shorter.
     |
     |      cmap : str or matplotlib Colormap, default='viridis'
     |          Colormap recognized by matplotlib.
     |
     |      ax : matplotlib Axes, default=None
     |          Axes object to plot on. If `None`, a new figure and axes is
     |          created.
     |
     |      colorbar : bool, default=True
     |          Whether or not to add a colorbar to the plot.
     |
     |      im_kw : dict, default=None
     |          Dict with keywords passed to `matplotlib.pyplot.imshow` call.
     |
     |      text_kw : dict, default=None
     |          Dict with keywords passed to `matplotlib.pyplot.text` call.
     |
     |          .. versionadded:: 1.2
     |
     |      Returns
     |      -------
     |      display : :class:`~sklearn.metrics.ConfusionMatrixDisplay`
     |
     |      See Also
     |      --------
     |      ConfusionMatrixDisplay.from_predictions : Plot the confusion matrix
     |          given the true and predicted labels.
     |
     |      Examples
     |      --------
     |      >>> import matplotlib.pyplot as plt
     |      >>> from sklearn.datasets import make_classification
     |      >>> from sklearn.metrics import ConfusionMatrixDisplay
     |      >>> from sklearn.model_selection import train_test_split
     |      >>> from sklearn.svm import SVC
     |      >>> X, y = make_classification(random_state=0)
     |      >>> X_train, X_test, y_train, y_test = train_test_split(
     |      ...         X, y, random_state=0)
     |      >>> clf = SVC(random_state=0)
     |      >>> clf.fit(X_train, y_train)
     |      SVC(random_state=0)
     |      >>> ConfusionMatrixDisplay.from_estimator(
     |      ...     clf, X_test, y_test)
     |      <...>
     |      >>> plt.show()
     |
     |      For a detailed example of using a confusion matrix to evaluate a
     |      Support Vector Classifier, please see
     |      :ref:`sphx_glr_auto_examples_model_selection_plot_confusion_matrix.py`
     |
     |  from_predictions(y_true, y_pred, *, labels=None, sample_weight=None, normalize=None, display_labels=None, include_values=True, xticks_rotation='horizontal', values_format=None, cmap='viridis', ax=None, colorbar=True, im_kw=None, text_kw=None)
     |      Plot Confusion Matrix given true and predicted labels.
     |
     |      For general information regarding `scikit-learn` visualization tools, see
     |      the :ref:`Visualization Guide <visualizations>`.
     |      For guidance on interpreting these plots, refer to the
     |      :ref:`Model Evaluation Guide <confusion_matrix>`.
     |
     |      .. versionadded:: 1.0
     |
     |      Parameters
     |      ----------
     |      y_true : array-like of shape (n_samples,)
     |          True labels.
     |
     |      y_pred : array-like of shape (n_samples,)
     |          The predicted labels given by the method `predict` of an
     |          classifier.
     |
     |      labels : array-like of shape (n_classes,), default=None
     |          List of labels to index the confusion matrix. This may be used to
     |          reorder or select a subset of labels. If `None` is given, those
     |          that appear at least once in `y_true` or `y_pred` are used in
     |          sorted order.
     |
     |      sample_weight : array-like of shape (n_samples,), default=None
     |          Sample weights.
     |
     |      normalize : {'true', 'pred', 'all'}, default=None
     |          Either to normalize the counts display in the matrix:
     |
     |          - if `'true'`, the confusion matrix is normalized over the true
     |            conditions (e.g. rows);
     |          - if `'pred'`, the confusion matrix is normalized over the
     |            predicted conditions (e.g. columns);
     |          - if `'all'`, the confusion matrix is normalized by the total
     |            number of samples;
     |          - if `None` (default), the confusion matrix will not be normalized.
     |
     |      display_labels : array-like of shape (n_classes,), default=None
     |          Target names used for plotting. By default, `labels` will be used
     |          if it is defined, otherwise the unique labels of `y_true` and
     |          `y_pred` will be used.
     |
     |      include_values : bool, default=True
     |          Includes values in confusion matrix.
     |
     |      xticks_rotation : {'vertical', 'horizontal'} or float,                 default='horizontal'
     |          Rotation of xtick labels.
     |
     |      values_format : str, default=None
     |          Format specification for values in confusion matrix. If `None`, the
     |          format specification is 'd' or '.2g' whichever is shorter.
     |
     |      cmap : str or matplotlib Colormap, default='viridis'
     |          Colormap recognized by matplotlib.
     |
     |      ax : matplotlib Axes, default=None
     |          Axes object to plot on. If `None`, a new figure and axes is
     |          created.
     |
     |      colorbar : bool, default=True
     |          Whether or not to add a colorbar to the plot.
     |
     |      im_kw : dict, default=None
     |          Dict with keywords passed to `matplotlib.pyplot.imshow` call.
     |
     |      text_kw : dict, default=None
     |          Dict with keywords passed to `matplotlib.pyplot.text` call.
     |
     |          .. versionadded:: 1.2
     |
     |      Returns
     |      -------
     |      display : :class:`~sklearn.metrics.ConfusionMatrixDisplay`
     |
     |      See Also
     |      --------
     |      ConfusionMatrixDisplay.from_estimator : Plot the confusion matrix
     |          given an estimator, the data, and the label.
     |
     |      Examples
     |      --------
     |      >>> import matplotlib.pyplot as plt
     |      >>> from sklearn.datasets import make_classification
     |      >>> from sklearn.metrics import ConfusionMatrixDisplay
     |      >>> from sklearn.model_selection import train_test_split
     |      >>> from sklearn.svm import SVC
     |      >>> X, y = make_classification(random_state=0)
     |      >>> X_train, X_test, y_train, y_test = train_test_split(
     |      ...         X, y, random_state=0)
     |      >>> clf = SVC(random_state=0)
     |      >>> clf.fit(X_train, y_train)
     |      SVC(random_state=0)
     |      >>> y_pred = clf.predict(X_test)
     |      >>> ConfusionMatrixDisplay.from_predictions(
     |      ...    y_test, y_pred)
     |      <...>
     |      >>> plt.show()
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object

    class DetCurveDisplay(sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin)
     |  DetCurveDisplay(*, fpr, fnr, estimator_name=None, pos_label=None)
     |
     |  Detection Error Tradeoff (DET) curve visualization.
     |
     |  It is recommended to use :func:`~sklearn.metrics.DetCurveDisplay.from_estimator`
     |  or :func:`~sklearn.metrics.DetCurveDisplay.from_predictions` to create a
     |  visualizer. All parameters are stored as attributes.
     |
     |  For general information regarding `scikit-learn` visualization tools, see
     |  the :ref:`Visualization Guide <visualizations>`.
     |  For guidance on interpreting these plots, refer to the
     |  :ref:`Model Evaluation Guide <det_curve>`.
     |
     |  .. versionadded:: 0.24
     |
     |  Parameters
     |  ----------
     |  fpr : ndarray
     |      False positive rate.
     |
     |  fnr : ndarray
     |      False negative rate.
     |
     |  estimator_name : str, default=None
     |      Name of estimator. If None, the estimator name is not shown.
     |
     |  pos_label : int, float, bool or str, default=None
     |      The label of the positive class. If not `None`, this value is displayed in
     |      the x- and y-axes labels.
     |
     |  Attributes
     |  ----------
     |  line_ : matplotlib Artist
     |      DET Curve.
     |
     |  ax_ : matplotlib Axes
     |      Axes with DET Curve.
     |
     |  figure_ : matplotlib Figure
     |      Figure containing the curve.
     |
     |  See Also
     |  --------
     |  det_curve : Compute error rates for different probability thresholds.
     |  DetCurveDisplay.from_estimator : Plot DET curve given an estimator and
     |      some data.
     |  DetCurveDisplay.from_predictions : Plot DET curve given the true and
     |      predicted labels.
     |
     |  Examples
     |  --------
     |  >>> import matplotlib.pyplot as plt
     |  >>> from sklearn.datasets import make_classification
     |  >>> from sklearn.metrics import det_curve, DetCurveDisplay
     |  >>> from sklearn.model_selection import train_test_split
     |  >>> from sklearn.svm import SVC
     |  >>> X, y = make_classification(n_samples=1000, random_state=0)
     |  >>> X_train, X_test, y_train, y_test = train_test_split(
     |  ...     X, y, test_size=0.4, random_state=0)
     |  >>> clf = SVC(random_state=0).fit(X_train, y_train)
     |  >>> y_score = clf.decision_function(X_test)
     |  >>> fpr, fnr, _ = det_curve(y_test, y_score)
     |  >>> display = DetCurveDisplay(
     |  ...     fpr=fpr, fnr=fnr, estimator_name="SVC"
     |  ... )
     |  >>> display.plot()
     |  <...>
     |  >>> plt.show()
     |
     |  Method resolution order:
     |      DetCurveDisplay
     |      sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, *, fpr, fnr, estimator_name=None, pos_label=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  plot(self, ax=None, *, name=None, **kwargs)
     |      Plot visualization.
     |
     |      Parameters
     |      ----------
     |      ax : matplotlib axes, default=None
     |          Axes object to plot on. If `None`, a new figure and axes is
     |          created.
     |
     |      name : str, default=None
     |          Name of DET curve for labeling. If `None`, use `estimator_name` if
     |          it is not `None`, otherwise no labeling is shown.
     |
     |      **kwargs : dict
     |          Additional keywords arguments passed to matplotlib `plot` function.
     |
     |      Returns
     |      -------
     |      display : :class:`~sklearn.metrics.DetCurveDisplay`
     |          Object that stores computed values.
     |
     |  ----------------------------------------------------------------------
     |  Class methods defined here:
     |
     |  from_estimator(estimator, X, y, *, sample_weight=None, drop_intermediate=True, response_method='auto', pos_label=None, name=None, ax=None, **kwargs)
     |      Plot DET curve given an estimator and data.
     |
     |      For general information regarding `scikit-learn` visualization tools, see
     |      the :ref:`Visualization Guide <visualizations>`.
     |      For guidance on interpreting these plots, refer to the
     |      :ref:`Model Evaluation Guide <det_curve>`.
     |
     |      .. versionadded:: 1.0
     |
     |      Parameters
     |      ----------

In [28]:
help(xgboost)

Help on package xgboost:

NAME
    xgboost - XGBoost: eXtreme Gradient Boosting library.

DESCRIPTION
    Contributors: https://github.com/dmlc/xgboost/blob/master/CONTRIBUTORS.md

PACKAGE CONTENTS
    _data_utils
    _typing
    callback
    collective
    compat
    config
    core
    dask (package)
    data
    federated
    libpath
    objective
    plotting
    sklearn
    spark (package)
    testing (package)
    tracker
    training

CLASSES
    abc.ABC(builtins.object)
        xgboost.core.DataIter
    builtins.object
        xgboost.core.Booster
        xgboost.core.DMatrix
            xgboost.core.ExtMemQuantileDMatrix(xgboost.core.DMatrix, xgboost.core._RefMixIn)
            xgboost.core.QuantileDMatrix(xgboost.core.DMatrix, xgboost.core._RefMixIn)
        xgboost.tracker.RabitTracker
    sklearn.base.BaseEstimator(sklearn.utils._repr_html.base.ReprHTMLMixin, sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin, sklearn.utils._metadata_requests._MetadataRequester)
        xgboost.sklearn.XGBModel
            xgboost.sklearn.XGBClassifier(sklearn.base.ClassifierMixin, xgboost.sklearn.XGBModel)
                xgboost.sklearn.XGBRFClassifier
            xgboost.sklearn.XGBRanker(xgboost.sklearn.XGBRankerMixIn, xgboost.sklearn.XGBModel)
            xgboost.sklearn.XGBRegressor(sklearn.base.RegressorMixin, xgboost.sklearn.XGBModel)
                xgboost.sklearn.XGBRFRegressor
    sklearn.base.ClassifierMixin(builtins.object)
        xgboost.sklearn.XGBClassifier(sklearn.base.ClassifierMixin, xgboost.sklearn.XGBModel)
            xgboost.sklearn.XGBRFClassifier
    sklearn.base.RegressorMixin(builtins.object)
        xgboost.sklearn.XGBRegressor(sklearn.base.RegressorMixin, xgboost.sklearn.XGBModel)
            xgboost.sklearn.XGBRFRegressor
    xgboost.sklearn.XGBRankerMixIn(builtins.object)
        xgboost.sklearn.XGBRanker(xgboost.sklearn.XGBRankerMixIn, xgboost.sklearn.XGBModel)

    class Booster(builtins.object)
     |  Booster(params: Union[List, Dict[str, Any], NoneType] = None, cache: Optional[Sequence[xgboost.core.DMatrix]] = None, model_file: Union[ForwardRef('Booster'), bytearray, os.PathLike, str, NoneType] = None) -> None
     |
     |  A Booster of XGBoost.
     |
     |  Booster is the model of xgboost, that contains low level routines for
     |  training, prediction and evaluation.
     |
     |  Methods defined here:
     |
     |  __copy__(self) -> 'Booster'
     |
     |  __deepcopy__(self, _: Any) -> 'Booster'
     |      Return a copy of booster.
     |
     |  __del__(self) -> None
     |
     |  __getitem__(self, val: Union[int, numpy.integer, tuple, slice, ellipsis]) -> 'Booster'
     |      Get a slice of the tree-based model. Attributes like `best_iteration` and
     |      `best_score` are removed in the resulting booster.
     |
     |      .. versionadded:: 1.3.0
     |
     |  __getstate__(self) -> Dict
     |      Helper for pickle.
     |
     |  __init__(self, params: Union[List, Dict[str, Any], NoneType] = None, cache: Optional[Sequence[xgboost.core.DMatrix]] = None, model_file: Union[ForwardRef('Booster'), bytearray, os.PathLike, str, NoneType] = None) -> None
     |      Parameters
     |      ----------
     |      params :
     |          Parameters for boosters.
     |      cache :
     |          List of cache items.
     |      model_file :
     |          Path to the model file if it's string or PathLike.
     |
     |  __iter__(self) -> Generator[ForwardRef('Booster'), NoneType, NoneType]
     |      Iterator method for getting individual trees.
     |
     |      .. versionadded:: 2.0.0
     |
     |  __setstate__(self, state: Dict) -> None
     |
     |  attr(self, key: str) -> Optional[str]
     |      Get attribute string from the Booster.
     |
     |      Parameters
     |      ----------
     |      key :
     |          The key to get attribute from.
     |
     |      Returns
     |      -------
     |      value :
     |          The attribute value of the key, returns None if attribute do not exist.
     |
     |  attributes(self) -> Dict[str, Optional[str]]
     |      Get attributes stored in the Booster as a dictionary.
     |
     |      Returns
     |      -------
     |      result : dictionary of  attribute_name: attribute_value pairs of strings.
     |          Returns an empty dict if there's no attributes.
     |
     |  boost(self, dtrain: xgboost.core.DMatrix, iteration: int, *, grad: Union[numpy.ndarray, Any, NoneType] = None, hess: Union[numpy.ndarray, Any, NoneType] = None, fobj: Optional[Callable[[numpy.ndarray, xgboost.core.DMatrix], Tuple[numpy.ndarray, numpy.ndarray]]] = None) -> None
     |      Boost the booster for one iteration with customized gradient statistics.
     |
     |      .. warning::
     |
     |          Like :py:meth:`.update`, this function should not be called directly by
     |          users.
     |
     |      Parameters
     |      ----------
     |      dtrain :
     |          The training DMatrix.
     |      iteration :
     |          The current training iteration.
     |      grad :
     |          The first order of gradient.
     |      hess :
     |          The second order of gradient.
     |      fobj :
     |          A custom objective function. If gradient is None, then an objective function
     |          is required.
     |
     |  copy(self) -> 'Booster'
     |      Copy the booster object.
     |
     |      Returns
     |      -------
     |      booster :
     |          A copied booster model
     |
     |  dump_model(self, fout: Union[str, os.PathLike], fmap: Union[str, os.PathLike] = '', with_stats: bool = False, dump_format: str = 'text') -> None
     |      Dump model into a text or JSON file.  Unlike :py:meth:`save_model`, the
     |      output format is primarily used for visualization or interpretation,
     |      hence it's more human readable but cannot be loaded back to XGBoost.
     |
     |      Parameters
     |      ----------
     |      fout :
     |          Output file name.
     |      fmap :
     |          Name of the file containing feature map names.
     |      with_stats :
     |          Controls whether the split statistics are output.
     |      dump_format :
     |          Format of model dump file. Can be 'text' or 'json'.
     |
     |  eval(self, data: xgboost.core.DMatrix, name: str = 'eval', iteration: int = 0) -> str
     |      Evaluate the model on mat.
     |
     |      Parameters
     |      ----------
     |      data :
     |          The dmatrix storing the input.
     |
     |      name :
     |          The name of the dataset.
     |
     |      iteration :
     |          The current iteration number.
     |
     |      Returns
     |      -------
     |      result: str
     |          Evaluation result string.
     |
     |  eval_set(self, evals: Sequence[Tuple[xgboost.core.DMatrix, str]], iteration: int = 0, feval: Optional[Callable[[numpy.ndarray, xgboost.core.DMatrix], Tuple[str, float]]] = None, output_margin: bool = True) -> str
     |      Evaluate a set of data.
     |
     |      Parameters
     |      ----------
     |      evals :
     |          List of items to be evaluated.
     |      iteration :
     |          Current iteration.
     |      feval :
     |          Custom evaluation function.
     |
     |      Returns
     |      -------
     |      result: str
     |          Evaluation result string.
     |
     |  get_categories(self, export_to_arrow: bool = False) -> xgboost._data_utils.Categories
     |      Same method as :py:meth:`DMatrix.get_categories`.
     |
     |  get_dump(self, fmap: Union[str, os.PathLike] = '', with_stats: bool = False, dump_format: str = 'text') -> List[str]
     |      Returns the model dump as a list of strings.  Unlike :py:meth:`save_model`,
     |      the output format is primarily used for visualization or interpretation, hence
     |      it's more human readable but cannot be loaded back to XGBoost.
     |
     |      Parameters
     |      ----------
     |      fmap :
     |          Name of the file containing feature map names.
     |      with_stats :
     |          Controls whether the split statistics should be included.
     |      dump_format :
     |          Format of model dump. Can be 'text', 'json' or 'dot'.
     |
     |  get_fscore(self, fmap: Union[str, os.PathLike] = '') -> Dict[str, Union[float, List[float]]]
     |      Get feature importance of each feature.
     |
     |      .. note:: Zero-importance features will not be included
     |
     |         Keep in mind that this function does not include zero-importance feature,
     |         i.e.  those features that have not been used in any split conditions.
     |
     |      Parameters
     |      ----------
     |      fmap :
     |         The name of feature map file
     |
     |  get_score(self, fmap: Union[str, os.PathLike] = '', importance_type: str = 'weight') -> Dict[str, Union[float, List[float]]]
     |      Get feature importance of each feature.
     |      For tree model Importance type can be defined as:
     |
     |      * 'weight': the number of times a feature is used to split the data across all
     |         trees.
     |      * 'gain': the average gain across all splits the feature is used in.
     |      * 'cover': the average coverage across all splits the feature is used in.
     |      * 'total_gain': the total gain across all splits the feature is used in.
     |      * 'total_cover': the total coverage across all splits the feature is used in.
     |
     |      .. note::
     |
     |         For linear model, only "weight" is defined and it's the normalized
     |         coefficients without bias.
     |
     |      .. note:: Zero-importance features will not be included
     |
     |         Keep in mind that this function does not include zero-importance feature,
     |         i.e.  those features that have not been used in any split conditions.
     |
     |      Parameters
     |      ----------
     |      fmap :
     |         The name of feature map file.
     |      importance_type :
     |          One of the importance types defined above.
     |
     |      Returns
     |      -------
     |      A map between feature names and their scores.  When `gblinear` is used for
     |      multi-class classification the scores for each feature is a list with length
     |      `n_classes`, otherwise they're scalars.
     |
     |  get_split_value_histogram(self, feature: str, fmap: Union[str, os.PathLike] = '', bins: Optional[int] = None, as_pandas: bool = True) -> Union[numpy.ndarray, ForwardRef('PdDataFrame')]
     |      Get split value histogram of a feature
     |
     |      Parameters
     |      ----------
     |      feature :
     |          The name of the feature.
     |      fmap:
     |          The name of feature map file.
     |      bin :
     |          The maximum number of bins.
     |          Number of bins equals number of unique split values n_unique,
     |          if bins == None or bins > n_unique.
     |      as_pandas :
     |          Return pd.DataFrame when pandas is installed.
     |          If False or pandas is not installed, return numpy ndarray.
     |
     |      Returns
     |      -------
     |      a histogram of used splitting values for the specified feature
     |      either as numpy array or pandas DataFrame.
     |
     |  inplace_predict(self, data: Any, *, iteration_range: Tuple[Union[int, numpy.integer], Union[int, numpy.integer]] = (0, 0), predict_type: str = 'value', missing: float = nan, validate_features: bool = True, base_margin: Any = None, strict_shape: bool = False) -> Union[numpy.ndarray, Any]
     |      Run prediction in-place when possible, Unlike :py:meth:`predict` method,
     |      inplace prediction does not cache the prediction result.
     |
     |      Calling only ``inplace_predict`` in multiple threads is safe and lock
     |      free.  But the safety does not hold when used in conjunction with other
     |      methods. E.g. you can't train the booster in one thread and perform
     |      prediction in the other.
     |
     |      .. note::
     |
     |          If the device ordinal of the input data doesn't match the one configured for
     |          the booster, data will be copied to the booster device.
     |
     |      .. code-block:: python
     |
     |          booster.set_param({"device": "cuda:0"})
     |          booster.inplace_predict(cupy_array)
     |
     |          booster.set_param({"device": "cpu"})
     |          booster.inplace_predict(numpy_array)
     |
     |      .. versionadded:: 1.1.0
     |
     |      Parameters
     |      ----------
     |      data :
     |          The input data.
     |      iteration_range :
     |          See :py:meth:`predict` for details.
     |      predict_type :
     |          * `value` Output model prediction values.
     |          * `margin` Output the raw untransformed margin value.
     |      missing :
     |          See :py:obj:`xgboost.DMatrix` for details.
     |      validate_features:
     |          See :py:meth:`xgboost.Booster.predict` for details.
     |      base_margin:
     |          See :py:obj:`xgboost.DMatrix` for details.
     |
     |          .. versionadded:: 1.4.0
     |
     |      strict_shape:
     |          See :py:meth:`xgboost.Booster.predict` for details.
     |
     |          .. versionadded:: 1.4.0
     |
     |      Returns
     |      -------
     |      prediction : numpy.ndarray/cupy.ndarray
     |          The prediction result.  When input data is on GPU, prediction result is
     |          stored in a cupy array.
     |
     |  load_config(self, config: str) -> None
     |      Load configuration returned by `save_config`.
     |
     |      .. versionadded:: 1.0.0
     |
     |  load_model(self, fname: Union[os.PathLike[~AnyStr], bytearray, str]) -> None
     |      Load the model from a file or a bytearray.
     |
     |      The model is saved in an XGBoost internal format which is universal among the
     |      various XGBoost interfaces. Auxiliary attributes of the Python Booster object
     |      (such as feature_names) are only saved when using JSON or UBJSON (default)
     |      format. Also, parameters that are not part of the model (like metrics,
     |      `max_depth`, etc) are not saved, see :doc:`Model IO </tutorials/saving_model>`
     |      for more info.
     |
     |      .. code-block:: python
     |
     |        model.save_model("model.json")
     |        model.load_model("model.json")
     |
     |        # or
     |        model.save_model("model.ubj")
     |        model.load_model("model.ubj")
     |
     |        # or
     |        buf = model.save_raw()
     |        model.load_model(buf)
     |
     |      Parameters
     |      ----------
     |      fname :
     |          Input file name or memory buffer(see also save_raw)
     |
     |  num_boosted_rounds(self) -> int
     |      Get number of boosted rounds.  For gblinear this is reset to 0 after
     |      serializing the model.
     |
     |  num_features(self) -> int
     |      Number of features in booster.
     |
     |  predict(self, data: xgboost.core.DMatrix, *, output_margin: bool = False, pred_leaf: bool = False, pred_contribs: bool = False, approx_contribs: bool = False, pred_interactions: bool = False, validate_features: bool = True, training: bool = False, iteration_range: Tuple[Union[int, numpy.integer], Union[int, numpy.integer]] = (0, 0), strict_shape: bool = False) -> numpy.ndarray
     |      Predict with data.  The full model will be used unless `iteration_range` is
     |      specified, meaning user have to either slice the model or use the
     |      ``best_iteration`` attribute to get prediction from best model returned from
     |      early stopping.
     |
     |      .. note::
     |
     |          See :doc:`Prediction </prediction>` for issues like thread safety and a
     |          summary of outputs from this function.
     |
     |      Parameters
     |      ----------
     |      data :
     |          The dmatrix storing the input.
     |
     |      output_margin :
     |          Whether to output the raw untransformed margin value.
     |
     |      pred_leaf :
     |          When this option is on, the output will be a matrix of (nsample,
     |          ntrees) with each record indicating the predicted leaf index of
     |          each sample in each tree.  Note that the leaf index of a tree is
     |          unique per tree, so you may find leaf 1 in both tree 1 and tree 0.
     |
     |      pred_contribs :
     |          When this is True the output will be a matrix of size (nsample,
     |          nfeats + 1) with each record indicating the feature contributions
     |          (SHAP values) for that prediction. The sum of all feature
     |          contributions is equal to the raw untransformed margin value of the
     |          prediction. Note the final column is the bias term.
     |
     |      approx_contribs :
     |          Approximate the contributions of each feature.  Used when ``pred_contribs``
     |          or ``pred_interactions`` is set to True.  Changing the default of this
     |          parameter (False) is not recommended.
     |
     |      pred_interactions :
     |          When this is True the output will be a matrix of size (nsample,
     |          nfeats + 1, nfeats + 1) indicating the SHAP interaction values for
     |          each pair of features. The sum of each row (or column) of the
     |          interaction values equals the corresponding SHAP value (from
     |          pred_contribs), and the sum of the entire matrix equals the raw
     |          untransformed margin value of the prediction. Note the last row and
     |          column correspond to the bias term.
     |
     |      validate_features :
     |          When this is True, validate that the Booster's and data's
     |          feature_names are identical.  Otherwise, it is assumed that the
     |          feature_names are the same.
     |
     |      training :
     |          Whether the prediction value is used for training.  This can effect `dart`
     |          booster, which performs dropouts during training iterations but use all
     |          trees for inference. If you want to obtain result with dropouts, set this
     |          parameter to `True`.  Also, the parameter is set to true when obtaining
     |          prediction for custom objective function.
     |
     |          .. versionadded:: 1.0.0
     |
     |      iteration_range :
     |          Specifies which layer of trees are used in prediction.  For example, if a
     |          random forest is trained with 100 rounds.  Specifying `iteration_range=(10,
     |          20)`, then only the forests built during [10, 20) (half open set) rounds are
     |          used in this prediction.
     |
     |          .. versionadded:: 1.4.0
     |
     |      strict_shape :
     |          When set to True, output shape is invariant to whether classification is
     |          used.  For both value and margin prediction, the output shape is (n_samples,
     |          n_groups), n_groups == 1 when multi-class is not used.  Default to False, in
     |          which case the output shape can be (n_samples, ) if multi-class is not used.
     |
     |          .. versionadded:: 1.4.0
     |
     |      Returns
     |      -------
     |      prediction : numpy array
     |
     |  reset(self) -> 'Booster'
     |      Reset the booster object to release data caches used for training.
     |
     |      .. versionadded:: 3.0.0
     |
     |  save_config(self) -> str
     |      Output internal parameter configuration of Booster as a JSON
     |      string.
     |
     |      .. versionadded:: 1.0.0
     |